# Generated by Django 5.2.9 on 2025-12-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
    ]
