# Generated by Django 5.2.9 on 2025-12-19 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_alter_music_album_alter_music_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='music',
            name='id',
        ),
        migrations.AddField(
            model_name='music',
            name='music_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
